# Maven
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription(1)(3dbc309e-5eba-4a66-a6ab-bf2175bdb0ce)'
    KeyVaultName: 'AldermanKV'
    SecretsFilter: '*'
    RunAsPreJob: false

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription(3dbc309e-5eba-4a66-a6ab-bf2175bdb0ce)'
    KeyVaultName: 'AldermanKV'
    SecretsFilter: '*'
    RunAsPreJob: false
